### ISSUE TITLE
햄버거 버튼이 작동하지 않는 문제

### ISSUE THREAD

**Issue by Kirade** [PilYeooong/WEB_HTML-CSS-JS#1]
<img width="101" alt="Screen Shot 2019-10-13 at 1 26 08 PM" src="https://user-images.githubusercontent.com/13049936/66710930-0b8e7c80-edbd-11e9-8df5-5b82e860f697.png">

800 이하 뷰에서 보여지는 햄버거버튼을 클릭해도 감추어진 메뉴가 보이지 않음

**Comment by pilyeooong** [comment]
https://github.com/PilYeooong/WEB_HTML-CSS-JS/commit/ee23857e20218ca75ab47a2ebf51c428772478bf

main.js 코드 수정을 하면서 코드 누락이 있었습니다. 
위의 커밋을 통해 버그를 수정하였습니다.
이슈 공유 감사드립니다.
